// Code generated by MockGen. DO NOT EDIT.
// Source: tmpl/interface.go

// Package mock_tmpl is a generated GoMock package.
package mock_tmpl

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMiddlewares is a mock of Middlewares interface
type MockMiddlewares struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewaresMockRecorder
}

// MockMiddlewaresMockRecorder is the mock recorder for MockMiddlewares
type MockMiddlewaresMockRecorder struct {
	mock *MockMiddlewares
}

// NewMockMiddlewares creates a new mock instance
func NewMockMiddlewares(ctrl *gomock.Controller) *MockMiddlewares {
	mock := &MockMiddlewares{ctrl: ctrl}
	mock.recorder = &MockMiddlewaresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMiddlewares) EXPECT() *MockMiddlewaresMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method
func (m *MockMiddlewares) GenerateToken(userId int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken
func (mr *MockMiddlewaresMockRecorder) GenerateToken(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockMiddlewares)(nil).GenerateToken), userId)
}
